### ISSUE TITLE
APT Error while build inside Eclipse: Unsupported location: CLASS_PATH

### ISSUE THREAD

**Issue by foal** [hal/elemento#40]
Command line generation is Ok, but in the Eclipse I see the error.

template class:
```java
@Templated("Todo.html#todos")
abstract class ApplicationElement implements IsElement<HTMLElement> {

	static ApplicationElement create() {
		return new Templated_ApplicationElement();
	}
}
```
html template:
```html
<section data-element="todos" class="todoapp">
   <h1>Hi</h1>
</section>
```
Stacktrace:
```
@Templated processor threw an exception: java.lang.IllegalArgumentException: Unsupported location: CLASS_PATH
	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getFileFromOutputLocation(IdeFilerImpl.java:186)
	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getResource(IdeFilerImpl.java:154)
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.parseTemplate(TemplatedProcessor.java:366)
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.processType(TemplatedProcessor.java:296)
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.onProcess(TemplatedProcessor.java:245)
	at elemento.shaded.org.jboss.auto.AbstractProcessor.process(AbstractProcessor.java:115)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:331)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:136)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by foal** [comment]
Just for reference:
https://github.com/immutables/immutables/issues/259
https://bugs.eclipse.org/bugs/show_bug.cgi?id=213540
>The only supported locations  are CLASS_OUTPUT and SOURCE_OUTPUT.

**Comment by hpehl** [comment]
Applying your fix https://github.com/foal/elemento/commit/ac48b2fcd440722c0b25ed36c356746213d185a4 breaks `mvn clean install` from the command line for samples/templated.

**Comment by hpehl** [comment]
Replacing the maven plugin `org.bsc.maven:maven-processor-plugin` with default compiler settings (APT auto detect) did the trick.
