### ISSUE TITLE
NullPointerException thrown in TemplatedProcessor

### ISSUE THREAD

**Issue by r0bnewt0n** [hal/elemento#67]
Occasionally I get the following exception in the Eclipse IDE.  I am using elemento 0.8.1 .

`
@Templated processor threw an exception: java.lang.NullPointerException
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.ancestorIsTemplated(TemplatedProcessor.java:669)
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.validateType(TemplatedProcessor.java:278)
	at org.jboss.gwt.elemento.processor.TemplatedProcessor.onProcess(TemplatedProcessor.java:243)
	at elemento.shaded.org.jboss.auto.AbstractProcessor.process(AbstractProcessor.java:115)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:110)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:937)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:447)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:423)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:383)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:368)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:315)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:183)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:140)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:276)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
`

**Comment by hpehl** [comment]
I'll try to take a look asap. Could you please try to specify "occasionally"? Are there certain prerequisites which cause the exception?

**Comment by r0bnewt0n** [comment]
The next time it happens I will note down the circumstances and relay to you.

**Comment by r0bnewt0n** [comment]
I have a feeling it was related to 2 different JDK's being used, accidently.  I had eclipse using 1.9 and maven using 1.8.  The JDK compiler was even dying at times.  If it happens again I will reopen and give better info.
